---
# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
# Commit
# Version 1.0.0
# Author: Vatu Ltd <hello@vatu.dev>

name: 'Commit'

on:
  workflow_dispatch:
  push:
    branches-ignore:
      - 'dependabot/**'
  pull_request:
    types:
      - opened
      - edited
      - synchronize

concurrency:
  group: ${{ github.workflow }}--${{ github.head_ref || github.ref_name }}
  cancel-in-progress: true

jobs:

  xml-lint:
    name: 'XML Lint'
    runs-on: 'ubuntu-latest'

    steps:

      - name: 'Check out the repository.'
        uses: 'actions/checkout@v4.1.1'

      - name: 'Download schema.'
        run: wget https://raw.githubusercontent.com/squizlabs/PHP_CodeSniffer/master/phpcs.xsd

      - name: 'Get lint information.'
        uses: 'korelstar/xmllint-problem-matcher@v1.2.0'

      - name: 'Run XML Lint tests.'
        uses: 'ChristophWurst/xmllint-action@v1.2'
        with:
          xml-file: ./phpcompatibility.dist.xml
          xml-schema-file: ./phpcs.xsd
